### ISSUE TITLE
warning for React.PropType

### ISSUE THREAD

**Issue by Pegahkeshavarz** [kenny-hibino/react-places-autocomplete#28] opened 2017-02-22 00:11 UTC
I am getting this warning after adding the component to my project:

Warning: You are manually calling a React.PropTypes validation function for the `autoFocus` prop on `PlacesAutocomplete`. This is deprecated and will not work in production with the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.

If you follow instruction in https://fb.me/react-warning-dont-call-proptypes , you can fix this warning  that everyone, who is using this library, is getting.

Thank you

**Comment by kenny-hibino** [comment] 2017-02-22 00:16
@Pegahkeshavarz Thanks for opening this issue! I will investigate this 👍

**Comment by Pegahkeshavarz** [comment] 2017-02-22 00:21
This warning is happening for all the props of the component. so i am getting like 12 warnings after using the component in my console.Thanks

**Comment by kenny-hibino** [comment] 2017-02-22 06:19
@Pegahkeshavarz I'm having trouble reproducing the error. Would you mind providing sample code to get the warning message in the console?

**Comment by Pegahkeshavarz** [comment] 2017-02-22 17:19
This is the code i am using:


  constructor(props){

    super(props);

    this.state={
      address: ''
    };
    this.onChange = this.onChange.bind(this);
  }

  onChange(address){
    this.setState({address});
  }

    render() {
      const cssClasses = {
        root: 'autoComplete-root',
        input: 'adventure-input-test',
        autocompleteContainer: 'autocomplete-container'
      }

        return (
                  <PlacesAutocomplete
                  value={this.state.address}
                  onChange={this.onChange}
                  placeholder={this.props.placeholder}
                  classNames={cssClasses}
                 
                />
        );
    }


"react": "15.0.2",
"react-dom": "15.0.2"
"react-places-autocomplete": "^3.0.0",

**Comment by Pegahkeshavarz** [comment] 2017-02-22 17:19
![screen shot 2017-02-22 at 9 19 28 am](https://cloud.githubusercontent.com/assets/15253917/23223493/118232e6-f8e0-11e6-926e-2a07ec30fafa.png)

**Comment by Pegahkeshavarz** [comment] 2017-02-22 17:21
It works and autocompletes the address but i am getting all these warnings in my console

**Comment by mskwarcan** [comment] 2017-02-24 11:33
The issue is explained here: https://facebook.github.io/react/warnings/dont-call-proptypes.html

It looks like a lot of this code will either need to be refactored or you'll need to use a different PropType library mentioned in the article.

`PlacesAutocomplete.propTypes = {
  value: React.PropTypes.string.isRequired,
  onChange: React.PropTypes.func.isRequired,
  onError: React.PropTypes.func,
  clearItemsOnError: React.PropTypes.bool,
  onSelect: React.PropTypes.func,
  placeholder: React.PropTypes.string,
  autoFocus: React.PropTypes.bool,
  autocompleteItem: React.PropTypes.func,
  classNames: React.PropTypes.shape({
    root: React.PropTypes.string,
    input: React.PropTypes.string,
    autocompleteContainer: React.PropTypes.string,
  }),
  styles: React.PropTypes.shape({
    root: React.PropTypes.object,
    input: React.PropTypes.object,
    autocompleteContainer: React.PropTypes.object,
    autocompleteItem: React.PropTypes.object,
    autocompleteItemActive: React.PropTypes.object
  }),
  options: React.PropTypes.shape({
    bounds: React.PropTypes.object,
    componentRestrictions: React.PropTypes.object,
    location: React.PropTypes.object,
    offset: React.PropTypes.oneOfType([
      React.PropTypes.number,
      React.PropTypes.string
    ]),
    radius: React.PropTypes.oneOfType([
      React.PropTypes.number,
      React.PropTypes.string
    ]),
    types: React.PropTypes.array
  })
}`

**Comment by goooseman** [comment] 2017-03-20 12:14
Is there any way to silence this warnings?

**Comment by goooseman** [comment] 2017-04-06 11:58
I was investigating the issue, and I can't really understand what is wrong. Looking at the documentation, we are using propTypes the right way, and it should not throw an error.

The problem is the mismatching of the React versions. In this library React v15.4.2 is hardcoded. And I was using 15.1.0. When I've updated to 15.4.2, the issue was gone.

Anyway, it is better not to hardcode exact version, but do smth like `>15.0.0`

**Comment by kenny-hibino** [comment] 2017-04-06 14:26
Big thank you to @goooseman ❤️

**Comment by bvellek** [comment] 2017-04-18 16:41
I apologize in advance if I am simply confused by the solution to this issue.

Wondering if it would be possible to add `prop-types`  library [package](https://www.npmjs.com/package/prop-types) so that this is compatible with future versions of React? As of [React v15.5](https://facebook.github.io/react/docs/typechecking-with-proptypes.html) `React.PropTypes` is deprecated. This will remove the error  and all you have to do is add the package where you are checking using `PropTypes`. If you don't do this, it is my understanding that anyone using new versions of React will receive that warning. Thanks!

**Comment by kenny-hibino** [comment] 2017-04-18 16:48
@bvellek I see. Would you mind creating a pull request for this? If not, I can get to it this weekend 👍

**Comment by bvellek** [comment] 2017-04-18 16:49
@kenny-hibino yeah sure thing! i will try to get to it later today. Thanks for the quick response!

**Comment by kenny-hibino** [comment] 2017-04-22 17:26
Closing this after PR #63

**Closed by kenny-hibino** 2017-04-22 17:26 UTC
