### ISSUE TITLE
Wrong LatLng

### ISSUE THREAD

**Issue by kkseven07** [kenny-hibino/react-places-autocomplete#160] opened 2018-01-24 07:40 UTC
Trying to search for "almaty gagarin 196" in demo, I got lat: 43.219...., lng: 76.897...
However, in my app, for exactly same search I got different coordinates(lat:43.2311..., lng:76.895..)
The difference is small, but it is very essential for my project. Why does this happen? I got different coordinates from demo for addresses, and the same for places(but not always)
My component
```
import React, { Component } from 'react';
import * as actions from '../../../actions';
import { connect } from "react-redux";
import {GoogleMapLoader, GoogleMap, Marker} from "react-google-maps";
import PlacesAutocomplete, { geocodeByAddress, getLatLng } from 'react-places-autocomplete'
import Input from '../../../components/ui/Input';

class Maps extends Component {
  state={address:'', mapCenter:{lat:43.2220146,lng:76.8512485}, curLocation:'Местоположение', coordsLat:43.2220146,coordsLng:76.8512485}
  
  onChange=(address)=>{
    this.setState({
      address:address
    })
  }
  shouldComponentUpdate(nextProps, nextState) {
    return shallowCompare(this, nextProps, nextState);
  }
  onFound=(latLng)=> {
    console.log("laltlng", latLng.lat, latLng.lng)
    this.setState({
      mapCenter:{lat:latLng.lat, lng:latLng.lng},
      coordsLat:latLng.lat,
      coordsLng:latLng.lng
      // coords:{lat:latLng.lat, lng:latLng.lng}
    })
  }

  handleCoordsLatChange(e){

     this.setState({
      // mapCenter:{lat:parseFloat(e.target.value.split(" ")[1]), lng:parseFloat(this.state.coordsLng)},
      coordsLat:e.target.value.split(" ")[1]?e.target.value.split(" ")[1]:''
    })
  }
  handleCoordsChange1(e){
    this.setState({
      // mapCenter:{lat:parseFloat(this.state.coordsLat), lng:parseFloat(e.target.value.split(" ")[1])},
      coordsLng:e.target.value.split(" ")[1]?e.target.value.split(" ")[1]:''
    })
  }
  handleSubmit=(e)=> {
    this.setState({
      curLocation:e,
      address:e
    })
  console.log("address", this.state.address)
  geocodeByAddress(this.state.address)
      .then(results => getLatLng(results[0]))
      .then(latLng => this.onFound(latLng))
      .catch(error => console.error('Error', error))
  }
  componentWillMount() {
    this.props.mapCenter&&
    this.setState({
      mapCenter:{lat:parseFloat(this.props.mapCenter.lat), lng:parseFloat(this.props.mapCenter.lng)},
      coordsLat:parseFloat(this.props.mapCenter.lat),
      coordsLng:parseFloat(this.props.mapCenter.lng)
    })

  }
  componentDidUpdate(prevProps, prevState) {
    // console.log("MAPCENTER", this.state.mapCenter, prevState.mapCenter)
    this.state.mapCenter!==prevState.mapCenter&&this.props.setCoords(this.state.mapCenter.lat, this.state.mapCenter.lng)

  }
  
  render() {
    // console.log("MAAAP", this.state.mapCenter)
    const inputProps = {
      value: this.state.address,
      onChange: this.onChange,
      type: 'search',
      charSet:"utf-8",
      placeholder: `Поиск адреса`,
    }
    return (
      <div style={{width:'85.3%'}}>

        <div className="curr-location"> <i className="map-marker-outline" ></i>{" "+ this.state.curLocation}</div>
        <div className="google-map">
          <GoogleMapLoader
            containerElement={
              <div
                style={{
                  height: 300,
                  width: "100%"
                }}
              />
            }
            googleMapElement={
              <GoogleMap
                defaultZoom={12}
                options={{mapTypeControl:false, streetViewControl:false}}
                // defaultCenter={{lat:this.state.mapCenter.lat , lng:this.state.mapCenter.lng}}
                center={{lat:this.state.mapCenter.lat , lng:this.state.mapCenter.lng}}
              >
                    <Marker 
                      draggable 
                      onDragend={e=>this.setState({mapCenter:{lat:e.latLng.lat(), lng:e.latLng.lng()}, coordsLat:e.latLng.lat(), coordsLng:e.latLng.lng()})} 
                      position={{lat:this.state.mapCenter.lat , lng:this.state.mapCenter.lng}} 
                    />

                {this.props.shops.shops.map((marker, i) => {
                  
                  return(
                    <Marker icon={{url:icon, scaledSize:{width:20, height:20}}} key={marker.name} position={{lat:marker.latitude, lng:marker.longitude}} />
                  );
                })}
              </GoogleMap>
            }
          />
        </div>

        <div className="map-search">
           <PlacesAutocomplete onSelect={e=>this.handleSubmit(e)} inputProps={inputProps} styles={{autocompleteContainer:{zIndex:'2'}}}/>
        </div>

        <div className="coords">
          <Input  style={{}}isFull value={"Широта: "+this.state.coordsLat} onFieldChange={(e)=>this.handleCoordsLatChange(e)}/>
          <Input  style={{}}isFull value={"Долгота: "+this.state.coordsLng} onFieldChange={(e)=>this.handleCoordsChange1(e)}/>
          <button 
            onClick={e=>this.setState({mapCenter:{lat:parseFloat(this.state.coordsLat), lng:parseFloat(this.state.coordsLng)}})}
          >
            <i className="fa fa-search" ></i>
          </button>
          
        </div>
      </div>

    );
  }
}

function mapStateToProps(state) {
  return {
    token:state.app.token,
    id:state.app.id,
    isSent: state.retailer.addSuccess,
    errors: state.retailer.errors,
    shops:state.shops,
    user:state.app


  };
}
export default connect(mapStateToProps)(Maps);


```
UPDATE: wrong place when I dont enter word:"street in russian(улица)".
Example: 
1."almaty gagarin 196" - wrong lat, lng
2."almaty street gagain 196" - right lat,lng.
In russian:
1. "алматы гагарина 196"
2. "алматы улица гагарина 196"

Can you fix it?

**Comment by impetus1** [comment] 2018-01-28 08:56
Is google maps 'pinning' to a specific location(place) when inputting that lat+lng?

**Comment by kkseven07** [comment] 2018-01-30 12:15
updated, found the bug.

**Comment by kenny-hibino** [comment] 2018-01-30 21:43
Closing this since it seems like it's not caused by the libarary

**Closed by kenny-hibino** 2018-01-30 21:43 UTC

**Comment by DanishWajid** [comment] 2019-03-06 08:20
@kkseven07  can you please tell me what's the bug ?
